### ISSUE TITLE
Scala 3 import handling issue

### ISSUE THREAD

**Issue by alexarchambault** [com-lihaoyi/Ammonite#1347]
Unexpectedly getting an error in the following scenario:
```text
$ scala-cli repl --amm --ammonite-version 3.0.0-M0-19-62705f47
Loading...
Welcome to the Ammonite Repl 3.0.0-M0-19-62705f47 (Scala 3.2.2 Java 1.8.0_362)

@ import $ivy.`com.lihaoyi::scalaparse:3.0.0`
import $ivy.$

@ import scalaparse.Scala._
import scalaparse.Scala._

@ 2
-- Error: cmd2.sc:60:2 ---------------------------------------------------------
60 |  TypePattern,
   |  ^^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:61:2 ---------------------------------------------------------
61 |  NotNewline,
   |  ^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:62:2 ---------------------------------------------------------
62 |  `<:`,
   |  ^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:63:2 ---------------------------------------------------------
63 |  `protected`,
   |  ^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:64:2 ---------------------------------------------------------
64 |  Semis,
   |  ^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:65:2 ---------------------------------------------------------
65 |  TypeArgList,
   |  ^^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:66:2 ---------------------------------------------------------
66 |  ClassQualifier,
   |  ^^^^^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:67:2 ---------------------------------------------------------
67 |  ValVarDef,
   |  ^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:68:2 ---------------------------------------------------------
68 |  WsCtx,
   |  ^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:69:2 ---------------------------------------------------------
69 |  StableId,
   |  ^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:70:2 ---------------------------------------------------------
70 |  OneNLMax,
   |  ^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:71:2 ---------------------------------------------------------
71 |  LocalMod,
   |  ^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:72:2 ---------------------------------------------------------
72 |  Import,
   |  ^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:73:2 ---------------------------------------------------------
73 |  BlockChunk,
   |  ^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:74:2 ---------------------------------------------------------
74 |  `if`,
   |  ^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:75:2 ---------------------------------------------------------
75 |  Pattern,
   |  ^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:76:2 ---------------------------------------------------------
76 |  NLAnnot,
   |  ^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:77:2 ---------------------------------------------------------
77 |  `match`,
   |  ^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:78:2 ---------------------------------------------------------
78 |  `lazy`,
   |  ^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:79:2 ---------------------------------------------------------
79 |  BlockLambda,
   |  ^^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:80:2 ---------------------------------------------------------
80 |  `object`,
   |  ^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:81:2 ---------------------------------------------------------
81 |  Id,
   |  ^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:82:2 ---------------------------------------------------------
82 |  notify,
   |  ^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:83:2 ---------------------------------------------------------
83 |  TypeDef,
   |  ^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:84:2 ---------------------------------------------------------
84 |  `<%`,
   |  ^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:85:2 ---------------------------------------------------------
85 |  QualId,
   |  ^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:86:2 ---------------------------------------------------------
86 |  `else`,
   |  ^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:87:2 ---------------------------------------------------------
87 |  `trait`,
   |  ^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:88:2 ---------------------------------------------------------
88 |  ArgList,
   |  ^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:89:2 ---------------------------------------------------------
89 |  PostfixType,
   |  ^^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:90:2 ---------------------------------------------------------
90 |  `var`,
   |  ^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:91:2 ---------------------------------------------------------
91 |  SimpleType,
   |  ^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:92:2 ---------------------------------------------------------
92 |  TrailingComma,
   |  ^^^^^^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:93:2 ---------------------------------------------------------
93 |  Ids,
   |  ^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:94:2 ---------------------------------------------------------
94 |  TypeArgs,
   |  ^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:95:2 ---------------------------------------------------------
95 |  hashCode,
   |  ^^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:96:2 ---------------------------------------------------------
96 |  `=>`,
   |  ^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:97:2 ---------------------------------------------------------
97 |  FreeCtx,
   |  ^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:98:2 ---------------------------------------------------------
98 |  Newline,
   |  ^^^^^^^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:99:2 ---------------------------------------------------------
99 |  `:`,
   |  ^
   |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:100:2 --------------------------------------------------------
100 |  StatCtx,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:101:2 --------------------------------------------------------
101 |  CaseClauses,
    |  ^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:102:2 --------------------------------------------------------
102 |  BindPattern,
    |  ^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:103:2 --------------------------------------------------------
103 |  VarId,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:104:2 --------------------------------------------------------
104 |  `super`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:105:2 --------------------------------------------------------
105 |  Constr,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:106:2 --------------------------------------------------------
106 |  PatLiteral,
    |  ^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:107:2 --------------------------------------------------------
107 |  `return`,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:108:2 --------------------------------------------------------
108 |  getClass,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:109:2 --------------------------------------------------------
109 |  `implicit`,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:110:2 --------------------------------------------------------
110 |  !=,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:111:2 --------------------------------------------------------
111 |  `@`,
    |  ^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:112:2 --------------------------------------------------------
112 |  wait,
    |  ^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:113:2 --------------------------------------------------------
113 |  Patterns,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:114:2 --------------------------------------------------------
114 |  AccessMod,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:115:2 --------------------------------------------------------
115 |  Annot,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:116:2 --------------------------------------------------------
116 |  ObjDef,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:117:2 --------------------------------------------------------
117 |  TmplBody,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:118:2 --------------------------------------------------------
118 |  PkgBlock,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:119:2 --------------------------------------------------------
119 |  AnonTmpl,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:120:2 --------------------------------------------------------
120 |  ne,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:121:2 --------------------------------------------------------
121 |  CaseBlock,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:122:2 --------------------------------------------------------
122 |  `this`,
    |  ^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:123:2 --------------------------------------------------------
123 |  BlockDef,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:124:2 --------------------------------------------------------
124 |  `yield`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:125:2 --------------------------------------------------------
125 |  TypePat,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:126:2 --------------------------------------------------------
126 |  BacktickId,
    |  ^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:127:2 --------------------------------------------------------
127 |  Block,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:128:2 --------------------------------------------------------
128 |  `private`,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:129:2 --------------------------------------------------------
129 |  BaseBlock,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:130:2 --------------------------------------------------------
130 |  `}`,
    |  ^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:131:2 --------------------------------------------------------
131 |  CompilationUnit,
    |  ^^^^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:132:2 --------------------------------------------------------
132 |  `with`,
    |  ^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:133:2 --------------------------------------------------------
133 |  ExistentialClause,
    |  ^^^^^^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:134:2 --------------------------------------------------------
134 |  ==,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:135:2 --------------------------------------------------------
135 |  Underscore,
    |  ^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:136:2 --------------------------------------------------------
136 |  TypeOrBindPattern,
    |  ^^^^^^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:137:2 --------------------------------------------------------
137 |  `macro`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:138:2 --------------------------------------------------------
138 |  Type,
    |  ^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:139:2 --------------------------------------------------------
139 |  CompoundType,
    |  ^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:140:2 --------------------------------------------------------
140 |  `import`,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:141:2 --------------------------------------------------------
141 |  InfixType,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:142:2 --------------------------------------------------------
142 |  `package`,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:143:2 --------------------------------------------------------
143 |  TypeId,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:144:2 --------------------------------------------------------
144 |  TopStatSeq,
    |  ^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:145:2 --------------------------------------------------------
145 |  TypeArg,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:146:2 --------------------------------------------------------
146 |  `extends`,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:147:2 --------------------------------------------------------
147 |  TrailingCommaOps,
    |  ^^^^^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:148:2 --------------------------------------------------------
148 |  `#`,
    |  ^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:149:2 --------------------------------------------------------
149 |  `do`,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:150:2 --------------------------------------------------------
150 |  `{`,
    |  ^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:151:2 --------------------------------------------------------
151 |  XmlExpr,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:152:2 --------------------------------------------------------
152 |  ExprCtx,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:153:2 --------------------------------------------------------
153 |  FunDef,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:154:2 --------------------------------------------------------
154 |  `forSome`,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:155:2 --------------------------------------------------------
155 |  isInstanceOf,
    |  ^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:156:2 --------------------------------------------------------
156 |  `try`,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:157:2 --------------------------------------------------------
157 |  Literals,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:158:2 --------------------------------------------------------
158 |  `override`,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:159:2 --------------------------------------------------------
159 |  TypeBounds,
    |  ^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:160:2 --------------------------------------------------------
160 |  `val`,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:161:2 --------------------------------------------------------
161 |  IdPath,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:162:2 --------------------------------------------------------
162 |  AnnotType,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:163:2 --------------------------------------------------------
163 |  PostDotCheck,
    |  ^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:164:2 --------------------------------------------------------
164 |  `class`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:165:2 --------------------------------------------------------
165 |  WS,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:166:2 --------------------------------------------------------
166 |  eq,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:167:2 --------------------------------------------------------
167 |  `new`,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:168:2 --------------------------------------------------------
168 |  `case`,
    |  ^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:169:2 --------------------------------------------------------
169 |  Dcl,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:170:2 --------------------------------------------------------
170 |  SimplePattern,
    |  ^^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:171:2 --------------------------------------------------------
171 |  BlockLambdaHead,
    |  ^^^^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:172:2 --------------------------------------------------------
172 |  `=`,
    |  ^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:173:2 --------------------------------------------------------
173 |  TraitDef,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:174:2 --------------------------------------------------------
174 |  ##,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:175:2 --------------------------------------------------------
175 |  `final`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:176:2 --------------------------------------------------------
176 |  EarlyDefTmpl,
    |  ^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:177:2 --------------------------------------------------------
177 |  Constrs,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:178:2 --------------------------------------------------------
178 |  `while`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:179:2 --------------------------------------------------------
179 |  notifyAll,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:180:2 --------------------------------------------------------
180 |  XmlPattern,
    |  ^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:181:2 --------------------------------------------------------
181 |  TopPkgSeq,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:182:2 --------------------------------------------------------
182 |  FunSig,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:183:2 --------------------------------------------------------
183 |  `abstract`,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:184:2 --------------------------------------------------------
184 |  `catch`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:185:2 --------------------------------------------------------
185 |  `throw`,
    |  ^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:186:2 --------------------------------------------------------
186 |  `def`,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:187:2 --------------------------------------------------------
187 |  WL0,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:188:2 --------------------------------------------------------
188 |  TypeExpr,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:189:2 --------------------------------------------------------
189 |  Pkg,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:190:2 --------------------------------------------------------
190 |  `for`,
    |  ^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:191:2 --------------------------------------------------------
191 |  `>:`,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:192:2 --------------------------------------------------------
192 |  `sealed`,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:193:2 --------------------------------------------------------
193 |  BlockExpr,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:194:2 --------------------------------------------------------
194 |  DefTmpl,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:195:2 --------------------------------------------------------
195 |  PkgObj,
    |  ^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:196:2 --------------------------------------------------------
196 |  NamedTmpl,
    |  ^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:197:2 --------------------------------------------------------
197 |  `type`,
    |  ^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:198:2 --------------------------------------------------------
198 |  ExprLiteral,
    |  ^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:199:2 --------------------------------------------------------
199 |  `finally`,
    |  ^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:200:2 --------------------------------------------------------
200 |  ParenArgList,
    |  ^^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:201:2 --------------------------------------------------------
201 |  WL,
    |  ^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:202:2 --------------------------------------------------------
202 |  ThisPath,
    |  ^^^^^^^^
    |  named imports cannot follow wildcard imports
-- Error: cmd2.sc:203:2 --------------------------------------------------------
203 |  `Underscore*`
    |  ^^^^^^^^^^^
    |  named imports cannot follow wildcard imports
Compilation Failed

@
```

**Comment by alexarchambault** [comment]
Things seem to work fine with Scala `2.13.10` (pass `--scala 2.13.10` to the `scala-cli` command above)
