### ISSUE TITLE
TASTy issues when compiling with Scala 2.13.6

### ISSUE THREAD

**Issue by keynmol** [com-lihaoyi/Ammonite#1182]
I'm not even sure where this problem will end up living long term.

  ```
  ❯ cat test-ammonite-issue.sc
  import scala.util.Try

  ❯ cs --help
  Coursier 2.0.16
  Usage: cs [options] [command] [command-options]

  Available commands: bootstrap, channel, complete, fetch, get, install, java, java-home, launch, list, publish, resolve, setup, uninstall, update, search

  Type  cs command --help  for help on an individual command

  ❯ cs launch ammonite --scala-version 2.13.6 -- test-ammonite-issue.sc
  Compiling /private/var/folders/m1/3py6pkgs3l1dvt3jpdht11nc0000gn/T/tmp.wbzaIVko/test-ammonite-issue.sc
  error while loading NotGiven, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in <...>/Library/Caches/Coursier/v1/https/repo1.  maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/NotGiven.class)', required by <...>/Library/Caches/Coursier/v  1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/NotGiven.class)
  error while loading FromDigits, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in <...>/Library/Caches/Coursier/v1/https/repo  1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/FromDigits.class)', required by <...>/Library/Caches/Coursi  er/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/FromDigits.class)
  error while loading CommandLineParser, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in <...>/Library/Caches/Coursier/v1/htt  ps/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/CommandLineParser.class)', required by <...>/Library  /Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/CommandLineParser.class)
  error while loading LowPriorityNotGiven, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in <...>/Library/Caches/Coursier/v1/h  ttps/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/LowPriorityNotGiven.class)', required by <...>/Lib  rary/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.jar(scala/util/LowPriorityNotGiven.class  )
  Compilation Failed
  ```

Seems like a regression, perhaps related to #1150?

As a side note, I noticed this issue running the following docker container:

```dockerfile
FROM openjdk:11

RUN apt install curl git

# https://get-coursier.io/docs/cli-overview.html#installation
RUN curl -Lo /usr/local/bin/coursier "https://github.com/coursier/coursier/releases/download/v2.0.16/coursier" \
  && chmod +x /usr/local/bin/coursier \
  && coursier --help

ENV PATH="$PATH:/root/.local/share/coursier/bin"

RUN coursier install sbt ammonite
```

And the default installation of ammonite (for 2.13.6, latest) breaks on my scripts.

**Comment by rtyley** [comment]
One thing I don't get about this bug is that it's giving this _"Add -Ytasty-reader to scalac options to parse the TASTy in..."_ error, and the `-Ytasty-reader` flag was introduced with https://github.com/scala/scala/pull/9293, which was merged and part of Scala 2.13.4. So why does this issue only occur when running with Scala 2.13.6, not 2.13.5 or 2.13.4?

So:

```
$ cs launch ammonite --scala-version 2.13.5 -- script.sc
```

...succeeds, but:

```
$ cs launch ammonite --scala-version 2.13.6 -- script.sc
```

...fails. I guess https://github.com/scala/scala/pull/9617 was released in Scala 2.13.6, though I don't immediately see how that would trigger the issue.

**Comment by adriaanm-da** [comment]
This issue is resolved by the 2.4.1 release.

**Comment by mpollmeier** [comment]
I can confirm that 2.4.1 works, thanks @adriaanm-da!

**Comment by dbear496** [comment]
I'm having this issue in Ammonite 2.5.9 with Scala 2.13.11.
