### ISSUE TITLE
upickle.default.macroRW not working in Ammonite Repl 2.5.11 (Scala 3.2.2 Java 17.0.8.1)

### ISSUE THREAD

**Issue by RGhosh1665** [com-lihaoyi/Ammonite#1390]
@ case class CustomerContext(isPaidMember: Boolean)
defined class CustomerContext

@ implicit val customerRW = upickle.default.macroRW[CustomerContext]
-- Error: cmd1.sc:1:13 ---------------------------------------------------------
1 |implicit val customerRW = upickle.default.macroRW[CustomerContext]
  |             ^
  |             type of implicit definition needs to be given explicitly
-- Error: cmd1.sc:1:26 ---------------------------------------------------------
1 |implicit val customerRW = upickle.default.macroRW[CustomerContext]
  |                          ^
  |Scala 2 macro cannot be used in Dotty. See https://docs.scala-lang.org/scala3/reference/dropped-features/macros.html
  |To turn this error into a warning, pass -Xignore-scala2-macros to the compiler
Compilation Failed
