### PR TITLE
Fix handling of imports involving synthetic case class objects

### LINKED ISSUE #474: implicit def should override all previous definitions
```
@ import $ivy.`com.chuusai::shapeless:2.3.2` 
import $ivy.$                             
@ import shapeless._ 
import shapeless._
@ implicit def :: = 1  
defined function ::
@ implicitly[Int]  
cmd5.sc:1: could not find implicit value for parameter e: Int
val res5 = implicitly[Int] 
                     ^
Compilation Failed
```

I expect  `::` defined in REPL should be taken over the imported `shapeless.::`, and the `implicitly[Int]` should work.

### PR DESCRIPTION
**Pull request by lihaoyi**
Fixes #474

Turns out that even though the companion object for a `case class Foo` is marked as synthetic, it can still be imported and used. Thus when determining imports, we should not filter out synthetic symbols

### CODE REVIEW

File: amm/repl/src/test/scala/ammonite/session/ImportTests.scala [hunk 1]
```diff
@@ -330,5 +330,25 @@ object ImportTests extends TestSuite{
...
+        @ import f.Foo
+
+        @ val Foo = 1
+
+        @ Foo
+      """)
+    }
+    test("shapelessBugFull"){
+      check.session("""
+        @ import $ivy.`com.chuusai::shapeless:2.3.2`, shapeless.::
```
Comment (alexarchambault) [inline amm/repl/src/test/scala/ammonite/session/ImportTests.scala:346]: For this to work with Scala 2.13:
```suggestion
        @ import $ivy.`com.chuusai::shapeless:2.3.7`, shapeless.::
```

File: amm/repl/src/test/scala/ammonite/session/ImportTests.scala [hunk 2]
```diff
@@ -330,5 +330,25 @@ object ImportTests extends TestSuite{
...
+        @ object f{ case class Foo()}
+
+        @ import f.Foo
+
+        @ val Foo = 1
+
+        @ Foo
+      """)
+    }
+    test("shapelessBugFull"){
```
Comment (alexarchambault) [inline amm/repl/src/test/scala/ammonite/session/ImportTests.scala:344]: I guess this test should be guarded by a `if (check.scala2)`, as shapeless basically [isn't the same project](https://github.com/typelevel/shapeless-3) in Scala 3.

**Review by alexarchambault — COMMENTED** [review]
Apart from what's mentioned in the comments, LGTM!

**Comment by lihaoyi** [comment]
@alexarchambault thanks for the pointers, test suite is green now
