### ISSUE TITLE
Error using flatmap operator

### ISSUE THREAD

**Issue by coverbeck** [com-lihaoyi/Ammonite#1103]
If you follow the Ammonite [grep documentation](https://ammonite.io/#grep), you get an error:

```
sys.props || grep! "os|OS".r  
cmd0.sc:1: value || is not a member of scala.sys.SystemProperties
val res0 = sys.props || grep! "os|OS".r 
                     ^
Compilation Failed
```

The documentation page itself has the same error. Interesting, I guess the doc itself is generated with ammonite.

![image](https://user-images.githubusercontent.com/1049340/87001479-65fe1300-c16c-11ea-90e7-6273dc62a251.png)

I tried a couple of older versions of Ammonite to see if the issue also happens there; it also doesn't work in version 2.1.3; it does work in 2.0.0 (that's all I tried).

**Comment by lihaoyi** [comment]
Superseded now that ammonite-ops is EOLed
